package POO;

import javax.swing.ImageIcon;


public class Carte extends javax.swing.JPanel {
    
    // Proprietes
    private int id;
    private String urlDos;
    private String urlFace;

    // Définition du constructeur
    // 1er parametre : vue de face de la carte
    // second paramétre : vue de dos de la carte
    // troisieme paramètre : id de la carte
    public Carte(String urlf, String urld, int ni) {
         // Affichage des composants créés en mode Design
         initComponents();
         // Initialisation des propriétés par les méthodes set
         setUrlDos(urld);
         setUrlFace(urlf);
         setId(ni);
         // Par défaut une carte affiche la vue de dos
         tournerVersDos();
    }
    
    public void setUrlFace(String tmp)
    {
        urlFace = tmp;
    }
    
    public void setUrlDos(String tmp)
    {
        urlDos = tmp;
    }
        
    public void setId(int tmp)
    {
        id = tmp;
    }
    
    
    public int getId()
    {
        return id;
    }    
        

    // Méthode métier qui affiche la photo associée à l'url passée paramètre
     public void affichePhoto(String tmp){
         ImageIcon icon = new ImageIcon(tmp);
         photoLbl.setIcon(icon);
     }
    
    public void tournerVersFace()
    {
        affichePhoto(urlFace);
    }
    
    public void tournerVersDos()
    {
        affichePhoto(urlDos);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photoLbl = new javax.swing.JLabel();

        photoLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        photoLbl.setPreferredSize(new java.awt.Dimension(57, 91));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(photoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel photoLbl;
    // End of variables declaration//GEN-END:variables
}
